### ISSUE TITLE
SVG Support?

### ISSUE THREAD

**Issue by akp37** [Hamza417/Inure#108]
![IP_0.jpg](https://user-images.githubusercontent.com/98131167/219418810-85368bdc-9457-4420-a049-4a9b125e046c.jpg)

I am getting this error when I try to view a SVG image.
I have the image saved in Downloads, I clicked on the file, selected Inure Image Viewer, and the error appears.

**Comment by Hamza417** [comment]
There's a native support for SVG, but..... I forgot to implement it into the Image Viewer. Thanks for bringing this to my attention, I'll add this before the next update.

**Comment by akp37** [comment]
Great, thanks! Loving your app

**Comment by Hamza417** [comment]
Added it, it'll be available in the next update.
