### ISSUE TITLE
Use system font.

### ISSUE THREAD

**Issue by rokejulianlockhart** [Hamza417/Inure#141]
**Is your feature request related to a problem? Please describe.**
The font currently hard-coded is difficult to read, and causes the application to appear inconsistent. However, this would also be a significant problem if any of my dyslexic friends were to need to use it, since some have already rooted their devices to be able to change the system font to a dyslexia-friendly version.

**Describe the solution you'd like**
Use the system font.

**Describe alternatives you've considered**
Allow the user to be able to choose to use the system font app-wide, but keep the current ones as the hard-coded *default*. Would make it instantly difficult for dyslexic people to navigate, though.

**Additional context**
https://github.com/Hamza417/Inure#apps-interface

**Comment by Hamza417** [comment]
Did you try changing to system font from _**Preferences > Appearances >App Typeface**_ ???

**Comment by rokejulianlockhart** [comment]
Somehow I'd changed it. It seems like, after reinstalling the app, the system default is even the default for the app now. Apologies.
