### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [Hamza417/Inure#156]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/4365496191#L405

ref: https://github.com/Hamza417/Inure/commit/8de742718fc7a0acd83db0d4b2b0f28c7776a052#diff-bad845415f942f9dc9954c3696508c88636fba0ef0124889a5c971565b841417

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/1d4b913fd88a8a59db18c34b51786c645290c48e

**Comment by Hamza417** [comment]
[rish_shizuku.dex](https://github.com/Hamza417/Inure/blob/master/app/src/main/assets/rish/rish_shizuku.dex) file is the culprit here, should it be ignored in the metadata file?

**Comment by licaon-kter** [comment]
I know who, the question is: what is that binary thing? Can we build it?

We can't just ignore it... imho.

**Comment by Hamza417** [comment]
@licaon-kter Most likely not, it's a pre-built Shizuku rish binary used to redirect the System Shell process to Shizuku in a Terminal client. I've recently added a native support for that hence the binary. Kindly, advice in the matter.

**Comment by linsui** [comment]
Where did you get the binary? It's a little different from the one extracted from https://github.com/RikkaApps/Shizuku/releases/tag/v13.2.1.

**Comment by Hamza417** [comment]
It's extracted from this build: https://github.com/RikkaApps/Shizuku/releases/tag/v13.3.0
I calculated the checksum, and it matched with this build. The [rish](https://github.com/Hamza417/Inure/blob/master/app/src/main/assets/rish/rish) file is a sh script for initialization, it's edited to include app package id as [suggested in the file](https://github.com/Hamza417/Inure/blob/c0aa76a407afd7b5c7de8de26a231fa844f82ec0/app/src/main/assets/rish/rish#L10-L11).

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13153 The dex file is reproducible.

**Comment by Hamza417** [comment]
I couldn't find any build reports. Does it require any action from my end?

**Comment by linsui** [comment]
No, this is fixed. You can see the pipeline in https://gitlab.com/linsui/fdroiddata/-/jobs/4368759127.

**Comment by licaon-kter** [comment]
Thanks @linsui
