### ISSUE TITLE
Ui border line

### ISSUE THREAD

**Issue by Baker0o7** [Hamza417/Inure#19]
On scroll up and down ![](https://i.imgur.com/GBh1EgM.png)![](https://i.imgur.com/6rQwM0e.png)![](https://i.imgur.com/5VcfACB.png)

**Comment by Hamza417** [comment]
@Baker0o7 I checked and it's a Recycler View implementation issue. I'll see if it can be fixed.

**Comment by Hamza417** [comment]
_This issue has been fixed now, and these changes will be reflected in the next release._
