### ISSUE TITLE
Small UI Animation Glitch

### ISSUE THREAD

**Issue by CeroaRAGZ** [Hamza417/Inure#199]
**Describe the bug**
When clicking a UI element that has an animated icon, it will overlay other UI elements when scrolling and take a position its not supposed to. I'll attach a video of the glitch.

**To Reproduce**
Click on any app in the viewer.
Scroll down immediately.
The icon takes unusual position then disappears. 

**Expected behavior**
The app or menu icons should slide up mid animation with the the text its supposed to be next to.

**Screenshots**
https://github.com/Hamza417/Inure/assets/112318871/e79e9960-4459-4d17-8d25-c2ab8706855c

**Smartphone (please complete the following information):**
 - Device: Irrelevant
 - OS: 12 AOSP
 - Version: Build86

**Additional context**
none

**Comment by Hamza417** [comment]
That's how animations in Android works.

**Comment by CeroaRAGZ** [comment]
Sorry. So is this a system level limitation?

**Comment by Hamza417** [comment]
> is this a system level limitation?

Yes, kind of. Android isn't written to be seamless in such situations. Views don't notify animators about any property changes, and animators are run as a separate entity that can manipulate view state. They don't really cooperate well under the hood, hence the glitch.

**Comment by CeroaRAGZ** [comment]
Ah, I understand. Inure functions like an interactive art piece, so this seemed a bit out of place.
