### ISSUE TITLE
Kindly small request 

### ISSUE THREAD

**Issue by Baker0o7** [Hamza417/Inure#21]
![Screenshot_20221029-154940_Inure_1](https://user-images.githubusercontent.com/113295927/198879435-9bc4fc26-de33-488a-81f8-558b6f5cb8d6.png)

ADD feature putting more icon like 4 , 5 or 6 instead of 3 each row thank you sir🙏

**Comment by Hamza417** [comment]
Using grid layout has some limitations, there's a width constraint to how much wider the view can get and having smaller width might crop the texts or icons on smaller screens.


| ![Screenshot_20221030-203301_Inure](https://user-images.githubusercontent.com/23103729/198885779-8e220d89-650b-48b7-9fda-6044a21cadf0.png) | ![Screenshot_20221030-203224_Inure](https://user-images.githubusercontent.com/23103729/198885868-17bc56d5-71c9-4a86-8a84-80c980769a70.png) |
|:---------------------------:|:---------------------------:|
|              Span => 5              |              Span => 4              |

**Comment by Hamza417** [comment]
I will be adding an app level custom grid configuration and this will allow to dynamically customize the span count of the grids throughout the app including app list. This should simultaneously address your issue as well.

**Comment by Hamza417** [comment]
> I will be adding an app level custom grid configuration and this will allow to dynamically customize the span count of the grids throughout the app including app list. This should simultaneously address your issue as well.

_This feature won't be added due to huge development load and has been deemed unnecessary._
