### ISSUE TITLE
Close button doesn't work

### ISSUE THREAD

**Issue by JustRedTTG** [Hamza417/Inure#229]
**Describe the bug**
In the boot manager sub menu when you tap on an app and then press close nothing happens

**To Reproduce**
1. Go to boot manager
2. Filter to enabled (unselect disabled) 
3. Click on any app (might only be for apps with 1 enabled boot action, might be for any app) 
4. Click close
5. Nothing happens

**Expected behavior**
The button should work as advertised and close the menu for enabling and disabling boot actions. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord 2T 5G
 - OS: OxygenOS 13.0
 - Version: CPH2399_11_C.27

**Additional context**

**Comment by Hamza417** [comment]
I forgot to add it, thanks for bringing this to my attention, It's fixed now ;)
