### ISSUE TITLE
 ERR: kotlin.collections.EmptyList Cannot be cast to java.util.Arraylist

### ISSUE THREAD

**Issue by TheBrokenG0d** [Hamza417/Inure#244]
**Describe the bug**
Opening the app at all has the error message appear at the bottom
"ERR: kotlin.collections.EmptyList Cannot be cast to java.util.Arraylist"

Clicking away makes the app work as intended, The error has always been there since I've installed the app.

**To Reproduce**
1. Open App
2. Error appears at bottom

**Expected behavior**
No Error

**Screenshots**
N/a

**Smartphone (please complete the following information):**
 - Pixel 7 Pro
 - Android 13 AOSP
 - Build92

**Additional context**
Using Shizuku method

**Comment by Hamza417** [comment]
It's a bug in Shizuku, restart your device and the bug should go away.

**Comment by TheBrokenG0d** [comment]
> It's a bug in Shizuku, restart your device and the bug should go away.

That was it. Thank you for the quick response.

**Comment by Hamza417** [comment]
I'm glad :)
