### ISSUE TITLE
Great app!  Questions and feature requests

### ISSUE THREAD

**Issue by snovvmann** [Hamza417/Inure#260]
Hi @Hamza417, nice and useful app! I see that you've put a lot of work into the visual experience too.

I have been looking for an app to replace MyAndroidTools. I use it (still, albeit not as reliable as before) to cut off receivers, services, trackers, start up on boot, etc. One of its best features is that it can backup all the cut off receivers, etc. configuration and restore them later. This is important because when an app gets updated, sometimes those changes I make gets reverted.

Another useful feature of MyAndroidTools is that it can present a list of all of the same services or receivers (e.g., boot receiver) so I can quickly disable them for the apps I want in batch.

So far, with what I see from Inure, I already know that I will be buying the premium version. I see a lot of potential for the app and I would like to see it continue to mature and be maintained for a long time to come. For people with root, this is an indispensable tool. Aside from the two examples I cite about MyAndroidTools, Inure does so much more and provides a lot more information, so I appreciate that.

Questions and feature requests:

1) In Inure's batch action, I see that I can select multiple apps and highlight them or move them to the top. **Is there anything else I can do with batch?** I would LOVE batch actions to, for example, set boot receivers (boot manger), set trackers, receivers, services, etc. Doing it one-by-one and long-pressing to make changes is time consuming and hard to track. Being able to see a list of all apps with specific receivers, etc. would be very helpful too.

2) **Can Inure backup and restore the receiver, tracker, etc. settings for the apps?** I do this with MyAndroidTools every so often so that updated apps with their settings changed can be restored as I want them. Facebook is one example where it sets some of the receivers each time it updates. It's very useful to be able to restore the settings and change the receivers back.

3) This one seems outside of Inure's scope, but I'll ask anyway. Current Android's app "optimization" is lackluster at times. For example, when I launch the Alexa app, it throws up a notification and remains running even when I exit the app. I have to force close the app to get it to stop running. **It would be nice to have a Greenify/Servicely-ish feature where specified apps are stopped when I am no longer using them.** Obviously, I am rooted.

Based on what I have seen so far, I would recommend Inure to those who have root and want to tweak. It has so many features!  **_I see below that there is a sponsor option.  In addition to buying the premium from Play Store, I would be willing to make donations if you can make some of these features happen._**

Anyway, thank you @Hamza417, for this wonderful and beautiful app--and very useful too! Very good work! I hope you find much success!

**Comment by Hamza417** [comment]
1. It's already in progress, I'm currently planning the Batch Tracker Control and [already added the option for this in the menu](https://github.com/Hamza417/Inure/blob/c5f9fd1b4b413c1b7031fd391acae46d3e6f8cef/app/src/main/java/app/simple/inure/constants/BottomMenuConstants.kt#L115) and whole framework to be implemented eventually before the next release, soon followed by Boot Manager as well.
2. Inure registers the trackers in IFW, you can preview the IFW file and export the list in XML and copy it back into the main app if needed, however IFW is permanent and any app cannot alter the settings except for the app that's created them, an app that's specialized in this, and the OS itself.
3. You can use Batch for this, I'm working on Batch profiles which will help organize different lists, and you won't have to check the app again and again for different tasks. The other way is to create a command shortcut and use terminal to kill these apps in one click. I'll add a dedicated option for this one in the future.

I'll be updating here as I progress through these. Thanks for the suggestions.

**Comment by snovvmann** [comment]
@Hamza417 thanks for the quick response.  

For #2, what I see is when FB updates, it reverts some of the receivers I disabled.  I guess in this case FB is the app that created them so it can make the changes.  Some apps, I believe, during update will check and make sure certain receivers and services are enabled.  This is why a save-and-restore feature would be great, one that backs up the config for all the apps and restores them all in one shot.  This is also useful when upgrading to a new phone.  It allows one to restore all the trackers, receivers, services settings without having to go to each app.

For #3, are you saying that the Batch profiles can run automatically?  It would be nice to have a service where if it "sees" an app on the list that is running, it will stop the app after the phone is turned off for a period of time.

If you are going to release a beta track, sign me up!

**Comment by Hamza417** [comment]
Sorry for late response, FB updates only be able to enable them if their names are changed or app enabled them deliberately, I'll implement a IFW based boot blocker in the next update which will render them useless even if they're enabled.

For other feature, I'll have to think about it, I'll keep you posted here as the development progresses.

**Comment by Hamza417** [comment]
> 1. It's already in progress, I'm currently planning the Batch Tracker Control and [already added the option for this in the menu](https://github.com/Hamza417/Inure/blob/c5f9fd1b4b413c1b7031fd391acae46d3e6f8cef/app/src/main/java/app/simple/inure/constants/BottomMenuConstants.kt#L115) and whole framework to be implemented eventually before the next release, soon followed by Boot Manager as well.
> 
>     2. Inure registers the trackers in IFW, you can preview the IFW file and export the list in XML and copy it back into the main app if needed, however IFW is permanent and any app cannot alter the settings except for the app that's created them, an app that's specialized in this, and the OS itself.
> 
>     3. You can use Batch for this, I'm working on Batch profiles which will help organize different lists, and you won't have to check the app again and again for different tasks. The other way is to create a command shortcut and use terminal to kill these apps in one click. I'll add a dedicated option for this one in the future.
> 
> 
> I'll be updating here as I progress through these. Thanks for the suggestions.

_Batch Tracker Control and Batch Profiles have been added in the [Build95](https://github.com/Hamza417/Inure/releases/tag/build95), subsequent features will be implemented as the development progresses._

**Comment by Hamza417** [comment]
If this thread still requires attention, could you please create these requests/suggestions under separate issues for better development prioritization.

**Comment by snovvmann** [comment]
> If this thread still requires attention, could you please create these requests/suggestions under separate issues for better development prioritization.

Yes.  I have not used the app for awhile.  I will do that when I get back into it.
