### ISSUE TITLE
Dedicated section for batch trackers with graphics

### ISSUE THREAD

**Issue by Bazoogle** [Hamza417/Inure#270]
**Is your feature request related to a problem?**
The current batch tracker block is difficult to find and access, and isn't easy/possible to see an overview of the trackers.

**Describe the solution you'd like**
On the main page, create a "Trackers" section. It would have some charts similar to those in the Analytics section that shows how many trackers there are, how many apps do/don't have trackers, what trackers there are. Additionally, it would act as the source for bulk blocking trackers, instead of going into the batch section and clicking the tiny hidden icon.

**Describe alternatives you've considered**
You could also just add the data to the analytics section, and keep them separate. Though I still think the batch trackers is quite hidden.

**Additional context**
I also think something for blocking trackers for newly installed apps would be nice. It could be included in the trackers section if added, or it could just be a toggle in the settings.

**Comment by Hamza417** [comment]
> I also think something for blocking trackers for newly installed apps would be nice. It could be included in the trackers section if added, or it could just be a toggle in the settings.

It's available in the **Installer** panel of the app.

**Comment by Hamza417** [comment]
The request involves recreating the Exodus app or pushes towards the imitation of the same, I'd suggest using their app for and only use Inure for scanning or blocking the trackers.
