### ISSUE TITLE
Navigation Bug

### ISSUE THREAD

**Issue by NikunjKhangwal** [Hamza417/Inure#277]
**Describe the bug**
The app randomly stop taking any inputs sometimes

**To Reproduce**
Just normal browsing of app

**Expected behavior**
The app should work normally

**Screenshots**
https://github.com/Hamza417/Inure/assets/99175083/6ddcd966-f5a8-4826-b057-4e5efe0839cb

The Keyboard is opening by tapping on any button
https://github.com/Hamza417/Inure/assets/99175083/f992266d-1a9c-4879-826d-77b765c58cf7

**Smartphone**
 - Device: Poco M2 (Redmi 9 Global)
 - OS: Android 12 MIUI 13
 - Version: Build95

**Comment by Hamza417** [comment]
The screen freezing issue is a [bug in Android APIs](https://issuetracker.google.com/issues/147749580), it can be fixed by turning off the **Transitions** from **Behavior** panel.

Could you tell me if there's any way to reproduce the keyboard issue?

**Comment by NikunjKhangwal** [comment]
No unfortunately, It happened out of sudden. Probably because of android api too ig.

**Comment by Hamza417** [comment]
@NikunjKhangwal Did you open any app from Search before the keyboard issue happened?

**Comment by NikunjKhangwal** [comment]
Nope

**Comment by Hamza417** [comment]
I haven't been able to reproduce this issue yet, I think it was a momentary glitch that occurred for some reason.

**Comment by Hamza417** [comment]
Hey, I was just to fix the issue, it was related to fragments' animations between the transactions.

**Comment by Hamza417** [comment]
The fix should be available in the next release now :)
I'm leaving the issue open until I properly test and fix other side effects, if any.

**Comment by NikunjKhangwal** [comment]
Cool. Thank you
