### ISSUE TITLE
Battery optimization 

### ISSUE THREAD

**Issue by NSTAdventure** [Hamza417/Inure#28]
Hi developer can you add feature to allow user control battery optimization directly from inure app?

Realme have problem on me where all list app disappeared without any trace
I was thinking such idea are possible since similar project have same feature

Thanks 🙏😊

**Comment by Hamza417** [comment]
@NSTAdventure If it's possible, I'll surely add it.

**Comment by Hamza417** [comment]
_Battery optimization (root only) has been added._

**Comment by NSTAdventure** [comment]
> _Battery optimization (root only) has been added._

Can't you add adb support for that sir?
(Since change battery optimization is possible with adb)

**Comment by Hamza417** [comment]
No, I won't. There's no way ADB environment can be created inside the app's context. There's a way to access Shell and it's called root, I don't know why you're so fixated on ADB.

**Comment by NSTAdventure** [comment]
> There's no way ADB environment can be created inside the app's context.

But sir app manager can do that
AM can change battery optimization with ADB over TCP privilege.

**Comment by Hamza417** [comment]
I have already mentioned the reason [here](https://github.com/Hamza417/Inure/issues/8#issuecomment-1322094288).

> I won't implement something half-baked into my app. ADB isn't made to run locally into the device and any implementation requires a lot of hacking or workarounds, and not to mention getting bug reports from “random mods” interfering with the app's state.

And here is _“one”_ of the reasons why, and this snap is taken from App Manager is itself if you've read the documentations of the app.
![Screenshot_20221126-203016_App_Manager](https://user-images.githubusercontent.com/23103729/204095561-5005a870-27d9-4749-8a93-91186ae51451.png)

And stop keep mentioning, _but the App Manager already does this_. App Manager is made on an entirely different foundation compared to what Inure is running on currently, and they both have different goals and purpose. If that app already does what you require, then go use that, don't waste my time.

And get rid of that _sir_ thing.

**Comment by NSTAdventure** [comment]
> 

Alright dev thanks 🙏

**Comment by Hamza417** [comment]
I've ported Battery Optimization for Shizuku.
