### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by CamsShaft** [Hamza417/Inure#281]
Thanks for this, enjoying it so far. I'm not sure if this is a bug but it just doesn't seem likely for it not to be. As you can see it's telling me root is available which is pretty much impossible since it's a snapdragon variant. Another possibility could be the fact that I've done some pretty rude things to this phone in my quest to root it and it's scrambled some things giving it a false reading?? Any ideas or if you've seen this yet?

![Screenshot_20240101-004601_Inure](https://github.com/Hamza417/Inure/assets/141678661/cb18e5c7-4c59-42e7-af69-7eeffd526668)

**Comment by Hamza417** [comment]
> which is pretty much impossible since it's a snapdragon variant.

Root isn't processor dependent

It's not possible to properly verify if the root is available or not since most of the efforts are put into hiding it from any detection. It maybe a bug but it can't be completely free of it either due the very nature of the root.

**Comment by CamsShaft** [comment]
That was quick! Huh, I guess I just placed rooting along with custom roms etc. I've been doing so much reading and feel I've got nowhere. Every time I think I've found a way around Samsung and Googles traps, something else is missing. Wish I had started learning this stuff years ago, I've probably been close and don't even know it. 🤷‍♂️

**Comment by Hamza417** [comment]
If you've granted root access to Inure, then it may also be possible for the app to detect it. Some custom ROMs also have su binary placed in the system, very unlikely but possible.

**Comment by CamsShaft** [comment]
That's also part of the mystery; your app won't even allow me to switch the root option to "on". I'm using shizuku mode but even before that it was still detecting root availability. And I don't have a custom rom either, my device is a galaxy s10 model G973U. Apparently because I can't unlock the bootloader I'm stuck with stock everything. It's a pretty strange instance and I'm honestly just curious if I actually can install the su binary. Not sure exactly how to go about figuring this out.

**Comment by Hamza417** [comment]
@CamsShaft The switch turns off automatically if the root connection cannot be established. If you're running a stock rom, then it's a false positive and can be safely ignored. Do you by any chance have [any of these apps](https://github.com/scottyab/rootbeer/blob/master/rootbeerlib/src/main/java/com/scottyab/rootbeer/Const.java)?

**Comment by CamsShaft** [comment]
Ahhh, that would make sense. Yes, I've tried all sorts of things. I suppose some of them left behind some data that inure is picking up? Even after factory reset there's probably still bits and pieces scattered around. Thanks for taking the time and lending your knowledge here! Sorry if it was a waste, I'm sure you have better things to do haha. Happy new year!

**Comment by Hamza417** [comment]
@CamsShaft No problem and a happy new year to you as well ❤️

**Comment by Hamza417** [comment]
@CamsShaft I'm not sure how those apps work but what I can say is they rely on system vulnerabilities to break security barrier and inject root binaries, you can run
su
command and check if it picks up root. Placing binary in the system alone won't grant you root access. Also any kind of modification in system will trip the KNOX (if I'm right) hence the warning from Samsung.

**Comment by CamsShaft** [comment]
Yeah I'll give the su command a shot. I haven't even attempted to get into /bin, since from what I've read, is nearly impossible especially for a somewhat novice like me. As for KNOX, this phone is surprisingly still alive and I've only soft bricked it once, I don't care about the warranty which is gone anyways. And if knox gets tripped I lose a few things I've never used. At least that's kinda what I've gathered. I briefly read something about a guy on xda I think that got a fastbootd token for development reasons and was able to unlock oem. Everything I've read with this phone always has the bootloader unlock in order to root, if I'm not mistaken anyways. Unless I'm really lucky and manage to fluke out and find a vulnerability I don't know how else to get there. At this point it's just a learning experience and if this thing turns into a heap of decompiled electronics so be it. I feel like I'm walking in circles whenever I google anything haha never any new information. Sorry if this is becoming a pain for you, thanks for your patience anyways!!

**Comment by Hamza417** [comment]
The only way I've been doing since years is patching the boot img and flashing it via fastboot or recovery, I'm not sure how it works in Samsung devices, you may have to look through your device's forums for better information regarding this.

**Comment by CamsShaft** [comment]
Every one that I've read on xda says the bootloader HAS to be unlocked to root. The only way to get fastboot is by obtaining a token directly from Samsung apparently, which I assume is very difficult to accomplish by itself. I'll check out some forums on the samsung website anyways. Thanks again and I'll keep you posted just for curiosity sake haha. If I happen to magically find a new way the people will make a damn statue of me! 😂
