### ISSUE TITLE
Execute command with adb support

### ISSUE THREAD

**Issue by NSTAdventure** [Hamza417/Inure#29]
Hi developer i have idea pls consider allow user using all adb shell command
With root or ADB privilege

Dev pls move this issues on discussion tab it's supposed to be there instead
Thanks 🙏😊

**Comment by Hamza417** [comment]
@NSTAdventure That's what the Terminal is for.

**Comment by NSTAdventure** [comment]
> @NSTAdventure That's what the Terminal is for.

Ikr but terminal can't execute adb shell command directly with root (or at least adb mode if exist)

**Comment by Hamza417** [comment]
> Or because i didn't rooted yet?

Both Yes and No. Running `pm` requires either root access or you've to set SELinux to `permissive`. Though, some OEMs don't allow their OSs to be in `permissive` state.

| ![Screenshot_20221113-015550_Inure](https://user-images.githubusercontent.com/23103729/201493258-039ea586-b440-4c6c-ae6a-5113ad43a7c7.png)  | ![Screenshot_20221113-015530_Inure](https://user-images.githubusercontent.com/23103729/201493259-83d1a32e-a815-493b-88f7-0dcff9e2d4a2.png) |
|:-----------------------------------:|:-----------------------------------:|
| Enforced | Permissive |

Also, you'll still be limited to what you can do with `pm` without root. Why not just root your device?

**Comment by NSTAdventure** [comment]
> Why not just root your device?

Dev i won't bothering you with adb support if i have 2nd devices..... I only have 1 it's realme
And realme isn't have wide range support for such  
That's my main devices used to work and other importan thing i won't risk it or else i can't work 💀

**Comment by Hamza417** [comment]
Ok, no problem, I'll add support for wireless debugging in Inure.
