### ISSUE TITLE
Some apps missing in search result

### ISSUE THREAD

**Issue by shunf4** [Hamza417/Inure#30]
![Screenshot_20221113154419](https://user-images.githubusercontent.com/20991618/201511445-d516e809-4c3c-46fb-8d65-4c9d68ae2f39.jpg)

---

![Screenshot_20221113154432](https://user-images.githubusercontent.com/20991618/201511443-8c0ecba3-5b03-4fcb-b84e-a75ac0ceea8f.jpg)

**Comment by Hamza417** [comment]
This is a known bug, I'm working on it.

**Comment by Hamza417** [comment]
I've fixed the issue. However, make sure you're filtering out the proper results as well from the search preferences, as this can also hide some search results.
