### ISSUE TITLE
Trackers

### ISSUE THREAD

**Issue by Baker0o7** [Hamza417/Inure#312]
Hi there kindly I'll like to suggest when you open in app section it will be nice to see trackers in main page instead of opening one app after another to see trackers thanks a lot for your hardworking to make the best app

**Comment by Hamza417** [comment]
This issue is [raised here](https://github.com/Hamza417/Inure/issues/270) already. However, it's one level deep, you can still use Batch Trackers to list all apps trackers at one place.

**Comment by Hamza417** [comment]
Refer to [this issue for any further updates](https://github.com/Hamza417/Inure/issues/270).
