### ISSUE TITLE
Trackers

### ISSUE THREAD

**Issue by Carlitos6904** [Hamza417/Inure#317]
Hi, because I don't have the window to deactivate trackers, I use shizucu
Samsung A 53 5g androis 14
![Screenshot_20240321_175545_Inure](https://github.com/Hamza417/Inure/assets/154341148/e8fe2c9a-84ca-4362-a23e-02b95634810d)

**Comment by Hamza417** [comment]
Tracker blocking is not available for Shizuku. You can check the list of things you can do using Shizuku [here](https://github.com/Hamza417/Inure/blob/master/FEATURES.md#shizuku-features).

**Comment by Carlitos6904** [comment]
thank you very much, I wasn't aware of the limitations of shizuku
