### ISSUE TITLE
Debloater: different colors for app state, method.

### ISSUE THREAD

**Issue by derei** [Hamza417/Inure#320]
In debloater apps list, it would make things much easier visually if method, for example, would have different colors, to quickly identify the removal safety concerns (Recommended, Advanced, Expert, Unsafe, Unlisted.

And for state (Enabled, Disabled, Uninstalled), same, each state to have associated a color.

Of course, this can be less of an issue when using very specific filters, but it really can come in handy with broader filters. Also, Inure already has a setting in Accessibility, for Colorful icons. That same setting could extend to app information.

![SmartSelect_20240324_134922_Inure](https://github.com/Hamza417/Inure/assets/34483372/e753fdfc-b7d9-46f5-a4c8-5ce3194a9970)

**Comment by Hamza417** [comment]
| ![Screenshot_20240325-013929_Inure_(Beta)](https://github.com/Hamza417/Inure/assets/23103729/b6a01e2a-b784-4f85-a914-3c8821ec8ce9) | ![Screenshot_20240325-013938_Inure_(Beta)](https://github.com/Hamza417/Inure/assets/23103729/50bab23a-f023-4500-9e6c-4087c3e3ff1a) |
|:--:|:--:|


This should work :)

**Comment by derei** [comment]
So, to show them with different background? Yes, it can definitely work.
My only concern was towards people preferring dark themes, to make it less intrusive.

**Comment by Hamza417** [comment]
Highlighting them completely works better in general, and I've added the toggles for all of them to allow for controls and sort of awareness towards what's highlighted and why. They can be disabled and are disabled by default.
