### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by vaimalaviya1233** [Hamza417/Inure#328]
**Is your feature request related to a problem? Please describe.**
yes, some of the features. I want to automate app disabling using tasker. etc...

**Describe the solution you'd like**
1) add tasker plugin code which allows to pick custom package or allow user to pass package address(ex. "com.reddit.frontpage") and allows user to pick action from drop down menu to choose one of any actions that are present when you visit app info page such as (ex. disable,enable, uninstall/reinstall, force-stop, launch, clear data, clear cache

2) upgrade review system - in google play version of app use google play in-app reviews API when it it supported such as in newer android version and keep the old design where it is not supported such as in older android systems.

3) option to open same app settings in different app such as in [AppOps](https://play.google.com/store/apps/details?id=rikka.appops), Greenify, [IceBox](https://play.google.com/store/apps/details?id=com.catchingnow.icebox), [Filterbox (show notifications filtered/filtered by searchbar not sure if possible/ might not be possible](https://play.google.com/store/apps/details?id=com.catchingnow.np), [Hail github link](https://github.com/aistra0528/Hail), [Hail F-droid (both apps is same just giving links)](https://f-droid.org/packages/com.aistra.hail/)

4) when in batch selection app screen If i tap search button that search does not bind to that batch selection meaning I cannot select 4-5 app by searching i have to manually scrolldown to that first letter of app name and select it. please make it bind to the batch selection and not go to universal search where i can't select multiple apps.

5)![clip](https://github.com/Hamza417/Inure/assets/55515799/dc1f724b-0a26-4419-843b-ffe0ac36c817)

6)![clip](https://github.com/Hamza417/Inure/assets/55515799/33d0a955-c7e3-4c3c-bd58-41dc153abc2d)

**Additional context**
I have taken notes here on nebo app I will put link here [Nebo page link](https://www.nebo.app/page/20d1deca-ca6c-4aba-b427-22a46cf44ccb)

**Comment by vaimalaviya1233** [comment]
I also think Feature requests should not be in issues but rather be in the discussions.

**Comment by Hamza417** [comment]
It'd be more appropriate to open each in their own dedicated issue. If you want to have a discussion start a discussion thread.

**Comment by vaimalaviya1233** [comment]
oops, really sorry I didn't know. I will create separate issue for feature request. :))
