### ISSUE TITLE
［question］How do you get the icons of uninstalled apps?

### ISSUE THREAD

**Issue by tokumei123456** [Hamza417/Inure#346]
Can anyone tell me how to make the icons of uninstalled apps show up?
The reason I want to know is because I want to implement that function in someone else's app.
Please take good care of me.
Sorry if this isn't the place to ask.

**Comment by Hamza417** [comment]
You can look [here](https://github.com/Hamza417/Inure/blob/master/app/src/main/java/app/simple/inure/glide/icon/AppIconFetcher.kt). I'd say look in the docs for this.

**Comment by tokumei123456** [comment]
Thank you for teaching me.
