### ISSUE TITLE
Sorting/Filter options in Tag pages

### ISSUE THREAD

**Issue by Crunchbits** [Hamza417/Inure#350]
**Is your feature request related to a problem? Please describe.**
When in a 'Tags' page, there is no option to sort or filter like you would in the regular 'Apps" page. This would be very useful especially for Tags with many apps.

**Solution**
Have the bottom menu present in 'Tag" pages with sorting/filter options.

**Alternatives**
Implement tags as a filter option in the regular 'Apps' page. Although, I would actually prefer this I don't know if it would be practical given the list in the Sort/Filter menu is pretty filled as shown below:

<img src="https://github.com/Hamza417/Inure/assets/87384615/4e5a95b1-594f-4ecf-afc2-a1877e644391" alt="Screenshot_20240622_150143_Inure" width="200">

**Comment by Hamza417** [comment]
It's not possible to implement a filter function is **Tags**. You can still use **#** in **Search** to filter through your tagged apps and search specifically within them.

![Untitled](https://github.com/Hamza417/Inure/assets/23103729/c7114251-a797-487a-b858-65b9efe90c2c)
