### ISSUE TITLE
Please add the Trackers Counter on the Apps List View Menu.

### ISSUE THREAD

**Issue by ZakMorphas** [Hamza417/Inure#351]
The trackers counter for each app is shown in the app details section. But not at the Apps menu. I've tried looking through Settings > Formatting > App Information, but the Trackers option is missing. It would be nice to filter apps by Trackers. 
Thank you.

**Comment by Hamza417** [comment]
Scanning for trackers is an expensive operation that's why it was only available in the Info panel. I'll check what can be done for that.

**Comment by ZakMorphas** [comment]
Oh. Okay, I understand. Thanks for replying.

**Comment by Hamza417** [comment]
I have added two things, Inure will now show a tracker icon next to apps with trackers throughout the app. And, I've added trackers count in App Menu as you've requested.

_Reference:_
![Screenshot_20240708-093330](https://github.com/Hamza417/Inure/assets/23103729/211b262d-9a27-4bf0-9886-082d90b3ab5a)

**Comment by ZakMorphas** [comment]
Thank you so much. I really appreciate it.
