### ISSUE TITLE
Filter Display of Apps By Permissions

### ISSUE THREAD

**Issue by MichaelDevon** [Hamza417/Inure#353]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
For example, option to display only the apps that have internet permission.

**Describe alternatives you've considered**
N/A

**Additional context**
Since there are lots of permissions, this may need a submenu.

**Comment by Hamza417** [comment]
@MichaelDevon You can do that using Deep Search

**Comment by MichaelDevon** [comment]
Oh. Thanks then.

**Comment by MichaelDevon** [comment]
Did i give you an idea? 😃

**Comment by MichaelDevon** [comment]
If i use Deep Search, can i only list System or User apps?

**Comment by Hamza417** [comment]
> Did i give you an idea? 😃

Yes, Deep Search could be improved. I'll be updating the improvements here.

> If i use Deep Search, can i only list System or User apps?

You can apply the same filters as Apps panel and perform the searches on the filtered dataset, including Tags if you do searches using hashtag #

**Comment by MichaelDevon** [comment]
Ohh i see. The sink icon. I thought it was part of the "open application settings" line.

![Screenshot_20240726-202429](https://github.com/user-attachments/assets/a5a1f7d4-056d-4a6c-93ba-6fb71723c1e5)

This could have its own line to avoid confusion.

**Comment by MichaelDevon** [comment]
Wait. Even though i selected System in the filter menu, apps are still showing from the user partition:
![Screenshot_20240726-202700](https://github.com/user-attachments/assets/1fbc35a6-cbcb-44df-903a-14f4a50e68d0)

I must be doing something wrong.

Im trying to make a search that only shows system apps with internet.

**Comment by Hamza417** [comment]
> Even though i selected System in the filter menu, apps are still showing from the user partition:

I checked, and it's filtering properly, can you show me your filter configurations for Search?

**Comment by MichaelDevon** [comment]
![Screenshot_20240727-092109](https://github.com/user-attachments/assets/2c0de359-c902-48ba-b847-d17de8b0b109)


I tried to mess around with it, and it seems that it only updates the list if i exit the app. Then on the next runtime it updates to the filters i selected propperly.
But for me, changing them while the app is open does nothing.

**Comment by Hamza417** [comment]
It was an issue in refreshing data that's causing it. I have fixed the issue and in the meantime you can **manually refresh the list** to refresh the properly filtered data. You don't need to restart the app, the refresh button will work the same.

**Comment by MichaelDevon** [comment]
Oh i see. Its strange that the list flashes upon selecting an option. I thought it was refreshing by itself.

My only suggestion is to move the filter button to its own line for UX.

Thank you for the help. I like this app.

**Comment by Hamza417** [comment]
> My only suggestion is to move the filter button to its own line for UX.

I'm still thinking about that. The placement of the button is off and doesn't match the UX of the app. I'll think of something.

I've also added lists of all permissions and trackers to easily look for queries to filter apps with specific permissions or trackers. This should make searching through apps easier.

**Comment by Hamza417** [comment]
I have added a collapsible menu in Search Box of Search panel. It'll allow me to add one or two button there without hurting the UI and make the filter button accessible. You'll also get to see a new, nice animation when you press the more button 😄
