### ISSUE TITLE
Terminal avalible after end of trial

### ISSUE THREAD

**Issue by Fleench** [Hamza417/Inure#366]
**Describe the bug**
If the terminal is opened as a seprate then after it tells you it's a premium feature you can reopen the terminal and have full access to it.

**To Reproduce**
1. Turn on standalone terminal
2. Have no active licence or trial
3. launch the terminal from the homescreeb
4. click close
5. reopen the terminal
6. use the terminal as normal

**Expected behavior**
The terminal is unusable without a licence or trial

**Screenshots**
![Screenshot_20240921_002153_Inure](https://github.com/user-attachments/assets/4ea457b4-c561-4956-b079-bd198971a95c)
![Screenshot_20240921_002121_Inure](https://github.com/user-attachments/assets/cda83ef0-6b31-439d-be2a-656adee4bdfd)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy s22 Ultra
 - OS: One UI 6.1(Android 14)
 - Version: Build 100.6.6-trial

**Additional context**
This only works with the standalone terminal.

**Comment by Hamza417** [comment]
It's patched now, thanks!!
