### ISSUE TITLE
[Bug] Remove second window appearing in landscape mode for editText.

### ISSUE THREAD

**Issue by Dinkarkumar** [Hamza417/Inure#380]
### Confirmation

- [X] I have read the [Code of Conduct](https://github.com/Hamza417/Inure/blob/master/CODE_OF_CONDUCT.md)
- [X] I have searched the existing issues

### Bug Description

Whenever editText is in focus mode in Landscape orientation, screen above keyboard is covered using another window. Hence causing inconvenience to user while seeing the live result of searched result.

### Steps to Reproduce

1. Open app.
2. Click on the Search icon.
3. Change to landscape mode.
4. Observe the white window appearing above the keyboard.

### Expected Behavior

White window should not appear above the keyboard.

### Screenshots

![1](https://github.com/user-attachments/assets/fe8e8297-7d20-43fb-b3ca-14d25ee1d5ff)

### Device Information

Reproducible in all devices.

### Sufficiency Confirmation

- [X] I have provided all the information requested above and deemed sufficient for the developer to address the issue

**Comment by Dinkarkumar** [comment]
I will add the fix for this issue.

**Comment by Hamza417** [comment]
@Dinkarkumar you can create a pull request.
