### ISSUE TITLE
Shared Preferences, error message

### ISSUE THREAD

**Issue by MichaelZ4714** [Hamza417/Inure#43]
I use Build49 and want to see the item Shared Preferences. An error message appears. Probably this can be handled a little more elegant.

My system is CrDroid 8.1 with microG 0.2.25.223616 and Magisk 25.2.

![Screenshot_20221124-095910_Inure](https://user-images.githubusercontent.com/63050301/203746494-dabc4f44-9ab4-4ad8-b743-6f66d3bb95f1.png)

**Comment by MichaelZ4714** [comment]
Here is the syslog [2022-11-24-12-02-42.zip](https://github.com/Hamza417/Inure/files/10085584/2022-11-24-12-02-42.zip). Is this what you need? I noticed that inside Inure in Preferences - Development there is the option Debug Features. But that's greyed out and can't be activated.

On the main page I noticed the screen Stacktraces. There is one other entry I can't remeber that it was displayed in the app as a message to the user on screen.

![Screenshot_20221124-160227_Inure](https://user-images.githubusercontent.com/63050301/203815985-e101b60f-e00f-44c6-9f8d-896c22641626.png)

**Comment by Hamza417** [comment]
_This issue has been fixed_
