### ISSUE TITLE
WebDav Apps Backup

### ISSUE THREAD

**Issue by Pantyhose-X** [Hamza417/Inure#73]
My phone doesn't have enough storage, I have 600 apps, how to export directly to PC?

export to [WebDAV](https://en.wikipedia.org/wiki/WebDAV), may be the only way to solve this problem.
PC run WebDAV server, Android Mount server

**Comment by Hamza417** [comment]
Why not extract the APKs and copy them to PC? or is there any requirement for them directly installing to PC through Inure?

**Comment by Pantyhose-X** [comment]
> Why not extract the APKs and copy them to PC? or is there any requirement for them directly installing to PC through Inure?

Device Not enough storage space

**Comment by Hamza417** [comment]
Could you elaborate the situation a bit more?

**Comment by Pantyhose-X** [comment]
> WebDAV

My Android device has no storage space.
It's too much trouble to back up to PC one by one
Backup all APKs directly to PC via WebDAV

**Comment by rokejulianlockhart** [comment]
This seems really niche. Just clear your storage, @Pantyhose-X.

**Comment by marcdw1289** [comment]
@Pantyhose-X 
You haven't provided certain bits of info. What is your device, ROM, Android version? Does the device support USB OTG? If so, hook a flash drive or external hard drive and use it as a backup destination.

Have you tried to free up storage space? Certain apps can build up hundreds of megabytes of cached data. Browsers, chat & social media, games, almost anything.
A few years back my old little device ran out of storage space. Discovered that the F-Droid client's cache was almost 1.5GB in size.
Check that stuff.

Provide the following...
1. Device and operating system.
2. Steps taken to improve your storage space issue.
3. Methods of backup you've tried.
3. Clearly state exactly what it is you expect the Dev or his app to do for you.

**Comment by Efreak** [comment]
Titanium backup and a number of other apps can backup apps directly to remote servers. If you need the apk files (titanium backup can't deal with the now-common split apks), I suggest [Neo Backup](https://github.com/NeoApplications/Neo-Backup), which natively uses SAF, so you can save backups to any source that has a SAF provider (WebDAV has next cloud app, there's SFTP and smb providers, and RCX for rclone).

**Comment by NikunjKhangwal** [comment]
There's also Swift Backup and DataBackup (fdroid)
