### ISSUE TITLE
per-release changelogs in Fastlane metadata

### ISSUE THREAD

**Issue by IzzySoft** [Hamza417/Inure#76]
The current changelogs just tell the user to look inside the app – which can only be done **after** it was updated. Could you please have the changelogs instead at least state the major changes? As they are now they're rather useless, as they are not "per release" but all identical.

**Comment by Hamza417** [comment]
Does your repo support/parse html tags from fastlane changelogs files?

**Comment by IzzySoft** [comment]
Fastlane Changelogs are treated as "pure ASCII" (though I run a HTML sanitizer over them, just in case, to protect my users). Newlines are replaced with `<br>` by fdroidserver when processing them. I'm not sure, but considering that other HTML formatting tags might work, too – though others will certainly be blocked there as well. You can try some simple tags with one changelog and then check the results – but start slowly so you can live with the results in either way – in case something runs `htmlentities()` over them, effectively turning each `<` into `&lt;` :see_no_evil:

**Comment by Hamza417** [comment]
> PS: And keep in mind the changelog files are limited to 500 char (and will be truncated at that point).

That's too less. Would linking to GitHub changelogs work? I can just add the link to changelogs available on GitHub.

**Comment by IzzySoft** [comment]
Linking would make the retrieval fail here (I've not yet implemented that as it is rarely used) – and even if:the results would be the same, no? Whatever is used as per-release changelog is limited to 500 chars. That's how Fastlane defines it – and thus how fdroidserver handles it. And it's IMHO definitely not too short, considering where it's usually displayed (right at the end of the description, so the user can find it easily).

The intention is to give a brief overview over the most important changes directly from within the client (i.e. without first following a link to some external document, and even working when offline). The full changelog can still be reached easily by following what is defined as `Changelog:` in the YAML (usually the `/releases` page, sometimes a `Changelog.md`). There you don't have a limit – though probably nobody would read a multi-page change list per release :wink:

**Comment by Hamza417** [comment]
Hmm, I still don't see how this could be relevant to user updating it or not. I'll add brief information about major changes with every release in fast lane metadata.

**Comment by Hamza417** [comment]
[This](https://github.com/Hamza417/Inure/blob/49e9fa84e4a84a0773ab0f98e55d67c8225d5f3f/fastlane/metadata/android/en-US/changelogs/59.txt) should do.

**Comment by IzzySoft** [comment]
PS: Just in case you wonder, my updater currently ignores your `full_description.txt` due to some minor formatting issues: your bullet-point lists would be broken:

```markdown
<b>Features</b>
 • Organized list of all apps
 • Usage stats of all apps
```

If you'd make that

```markdown
<b>Features</b>

* Organized list of all apps
* Usage stats of all apps
```

it would work excellently. That is: an empty line before and after bullet-point lists, and using either `*` or `-` as bullet points. I could of course take it as-is, just replacing `\n` with `<br>` as F-Droid (and probably also PlayStore) do, if you prefer that – but then it looks ugly on smaller screens (due to wrapping of longer bullet-point items). If you want that let me know and I'll do; otherwise if you'd do those small adjustments there, my updater can process it properly as Markdown, which looks much nicer (not only on small screens) – let me know that then as well so I can adjust my config here accordingly.

**Comment by Hamza417** [comment]
[Updated](https://github.com/Hamza417/Inure/blob/8ef74e4c9df20ff9adfe80908f9d98149b86801f/fastlane/metadata/android/en-US/full_description.txt) the formatting as you've prescribed, could you check it if there's any issue?

**Comment by IzzySoft** [comment]
That looks perfect, thanks! Let me enable it here and force an update to make sure (frowning a bit.ly on that link, but :man_shrugging:)… Yupp, seems to work fine. Just the links are not linkified (you can use `<a href=` if you wish, it's white-listed with my repo and with F-Droid.org as well, though some attributes like `onClick` would be sanitized).

Thanks! So full description will now be updated along with new releases, when changed.

**Comment by Hamza417** [comment]
I'll fix the links by the next release too and will remove the bitly as well.

**Comment by IzzySoft** [comment]
Thanks a lot! Will be pulled then along with the APK – so 24h later (more precisely: my updater starts collecting around 6:30 pm UTC, with results usually becoming available around 7 pm UTC) you can cross-check the results. Should something not match expectations, feel free to give me a ping.
