### ISSUE TITLE
Visibility issues

### ISSUE THREAD

**Issue by alpha4041** [Hamza417/Inure#77]
I have visibility issues with the dark theme on some information sections of the settings:
![Screenshot_20230112-225856_Inure](https://user-images.githubusercontent.com/88579269/212190286-48b8ee38-bc00-489e-8718-f219ffbcc4b0.png)
![Screenshot_20230112-225902_Inure](https://user-images.githubusercontent.com/88579269/212190300-639a4bfc-dc0c-4bd5-b825-b9b132850e32.png)
![Screenshot_20230112-225908_Inure](https://user-images.githubusercontent.com/88579269/212190319-c6d843c2-7cc2-48ec-a9a8-c09b2920caf7.png)

**Comment by Hamza417** [comment]
This issue is already fixed in 1a7c6a0.

**Comment by alpha4041** [comment]
okay, sorry, my bad
