### ISSUE TITLE
Add option to install apps with root

### ISSUE THREAD

**Issue by alpha4041** [Hamza417/Inure#78]
I use the Inure app installer when opening apks, but I think it would be better if it supported silent root installations.

**Comment by Hamza417** [comment]
Root mode is not added yet. It's planned, and I'll add that later when I have the time.

> I also suggest to add options like viewing the installer response on errors

Could you elaborate this part, you mean saving installation report in **Stacktraces**?

**Comment by alpha4041** [comment]
> Root mode is not added yet. It's planned, and I'll add that later when I have the time.
> 
> > I also suggest to add options like viewing the installer response on errors
> 
> Could you elaborate this part, you mean saving installation report in **Stacktraces**?

Sorry, I don't know if the installer already displays the response error if installation fails. I mean this

**Comment by Hamza417** [comment]
Yes, _Installer_ shows the proper error response if the process fails due to some reason.

**Comment by Hamza417** [comment]
| ![Screenshot_20230113-143430_Inure](https://user-images.githubusercontent.com/23103729/212281207-70e2008f-e37c-4d5c-b2fb-aaed5c9c727a.png) | ![Screenshot_20230113-143442_Inure](https://user-images.githubusercontent.com/23103729/212281409-3b2ec0c5-222a-4682-9557-f64a6ae3705b.png) |
|:---------------------------:|:---------------------------:|

It looks like this.

**Comment by alpha4041** [comment]
> | ![Screenshot_20230113-143430_Inure](https://user-images.githubusercontent.com/23103729/212281207-70e2008f-e37c-4d5c-b2fb-aaed5c9c727a.png) | ![Screenshot_20230113-143442_Inure](https://user-images.githubusercontent.com/23103729/212281409-3b2ec0c5-222a-4682-9557-f64a6ae3705b.png) |
> |:---------------------------:|:---------------------------:|
> 
> It looks like this.
> 
> 
> 
> 

okay, sorry again for suggesting a thing that was already there.

**Comment by Efreak** [comment]
I'd like to suggest Shizuku or ADB support as an alternative to root.

**Comment by Hamza417** [comment]
I'm working on both and testing which gives the best UX in terms of usability.

**Comment by Efreak** [comment]
I prefer Shizuku personally, but if you're implementing ADB

1. Shizuku does have a way to grab the current port so it doesn't have to be entered manually (very much preferred). [Here](https://github.com/RikkaApps/Shizuku/blob/bc29dd17b286ad0b623a0341df2de397cbad5757/manager/src/main/java/moe/shizuku/manager/home/AdbDialogFragment.kt#L73), I think.

2. ADB pairing needs a way to enter the code without leaving the developer settings screen
  - App Manager wants the user to [split the screen](https://muntashirakon.github.io/AppManager/en/#subsec:pair-adb-with-app-manager
  - Shizuku pops a [notification with a text input](https://shizuku.rikka.app/guide/setup/#start-via-wireless-debugging))
    - @MuntashirAkon says that [notifications do not work on some devices](https://github.com/MuntashirAkon/AppManager/issues/892#issuecomment-1283324082) (this doesn't really surprise me)
  - A third option might be to use a [floating bubble](https://developer.android.com/develop/ui/views/notifications/bubbles), but [Bubbles are created via the Notification API](https://developer.android.com/develop/ui/views/notifications/bubbles#the_bubble_api), so would probably not work in the same places as Shizuku's method
  - I would tend to expect [SYSTEM_ALERT_WINDOW](https://medium.com/exploring-code/create-chat-heads-like-facebook-messenger-32f7f1a62064) to work, but i who knows? It does need [permission](https://developer.android.com/reference/android/Manifest.permission.html#SYSTEM_ALERT_WINDOW) to be granted explicitly these days
    - not sure if this would be allowed in the play store. I thought it had been disallowed, but can't find anything on this now
    - is adb settings considered a [sensitive screen](https://developer.android.com/about/versions/12/features#hide-application-overlay-windows)? I know there was a thing about windows covering the package installer.
    - [Google started restricting the areas in which overlays can draw back in Android Oreo, and they've completely removed access to the API for Android Q (Go Edition.........In Android Q, access to the SYSTEM_ALERT_WINDOW permission is transient: side-loaded apps only have access to the permission for 30 seconds.........in a future Android release, SYSTEM_ALERT_WINDOW will be fully deprecated](https://www.xda-developers.com/android-q-system-alert-window-deprecate-bubbles/) not sure if the pushback on this has changed anything (Bubbles are supposed to replace it, but Bubbles are notifications and can't be used for, say, a sticky notes app)

**Comment by Hamza417** [comment]
I'll be implementing Shizuku given how complicated ADB implementation can get, Shizuku seems an ideal choice.

**Comment by Hamza417** [comment]
I've added implementation for root installation. Shizuku was added as well, but isn't working at the moment.

**Comment by Hamza417** [comment]
Shizuku is fixed as well.
