### ISSUE TITLE
Adb

### ISSUE THREAD

**Issue by bornhustler07** [Hamza417/Inure#8]
Hi sir first of all thank you for your hard work I'll like to ask can you add adb root method for those who are not rooted 👍

**Comment by Hamza417** [comment]
@bornhustler07 I have this planned already and it will be added soon in the app.

**Comment by Hamza417** [comment]
@bornhustler07 Could you suggest me some app that uses this feature and if possible open source?

**Comment by bornhustler07** [comment]
Just your app is enough I mean your can use adb to uninstall system app and adb to control apps permission

**Comment by bornhustler07** [comment]
Something like permission manager x

**Comment by bornhustler07** [comment]
And batch uninstaller

**Comment by bornhustler07** [comment]
Over all your app is just wonderful sir thanks again :pray:

**Comment by Hamza417** [comment]
Thanks, I'll have to learn about this first and will update here once I begin adding this feature.

**Comment by NSTAdventure** [comment]
> @bornhustler07 I have this planned already and it will be added soon in the app.

Hi dev can you also add shizuku mode?
But pls make sure it's available even shizuku run via adb mode 

Thanks for your consideration
🙏😊

**Comment by Ilithy** [comment]
>Thanks, I'll have to learn about this first and will update here once I begin adding this feature.

Hi, if it helps, the [Scoop](https://github.com/TacoTheDank/Scoop) app uses this method (authorization via adb rather than root), and it's open source :-)

The method of use for users is it available [here](https://github.com/TacoTheDank/Scoop/wiki#instructions-for-non-rooted-users)

**Comment by Hamza417** [comment]
> Hi, if it helps, the [Scoop](https://github.com/TacoTheDank/Scoop) app uses this method (authorization via adb rather than root), and it's open source :-)
> 
> The method of use for users is it available [here](https://github.com/TacoTheDank/Scoop/wiki#instructions-for-non-rooted-users)

Thanks for the source, I've read it, and It's for granting READ_LOGS permission using ADB. Currently, there's no possible or straight forward method to execute ADB commands from inside an app.

**Comment by Hamza417** [comment]
I've also checked [LADB](https://github.com/tytydraco/LADB) and the app does exactly that, however the workaround list just to have it up and running is too big and not feasible for implementation in Inure where user experience is the end goal.

**Comment by NSTAdventure** [comment]
> _I've also checked [LADB](https://github.com/tytydraco/LADB) and the app does exactly that, however the workaround list just to have it up and running is too big and not feasible for implementation in Inure where user experience is the end goal._

... It's paid and i can't build or compile apk from source 🥴

**Comment by Hamza417** [comment]
> It's paid and i can't build or compile apk from source

That's not my problem. It legit sucks though that you cannot pay 2 dollars for an app.

> Also can't run alongside with shizuku i won't uninstall shizuku bcs some my app need it.

Again, not my problem. I don't even know what Shizuku is. I made myself clear that I won't implement something half-baked into my app. ADB isn't made to run locally into the device and any implementation requires a lot of hacking or workarounds, and not to mention getting bug reports from “random mods” interfering with the app's state. Just root your device already if you need these functionalities that badly.

**Comment by Hamza417** [comment]
_Despite my previous stance on ADB, Shizuku support has been added in the recent updates._
